version: '3.8'
services:
  postgres:
    image: postgres:11
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "database", "-U", "root" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tomcat:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
