database:
  username: root
  password: root
  url: jdbc:postgresql://postgres:5432/database
  driver-class-name: org.postgresql.Driver
  initialize-db: true
  sql-path: liquibase/db-changelog.sql
cache:
  capacity: 5
  type: lru
